name: XcodeBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build App
      run: xcodebuild -project "Dice.xcodeproj" -scheme "Dice" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
      

